[package]
name = "cupid-desktop"
version = "0.1.0"
edition = "2024"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
cupid = { path = "../crates/cupid-core" }
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
postgres = "0.19.14"
native-tls = "0.2.18"
postgres-native-tls = "0.5.3"
time = { version = "0.3", features = ["formatting"] }
